name: Build Server

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Builds
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Execute `cargo build`
        run: cargo build --release
