name: Build Web

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Builds
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Build Web Crate
        run: just web-build
