name: clippy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Code Best Practices
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Execute `cargo clippy`
        run: cargo clippy
