name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Unit Tests
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Execute `cargo test`
        run: cargo test
